### ISSUE TITLE
Rounds incorrectly

### ISSUE THREAD

**Issue by vi-k** [AKushWarrior/starfruit#1]
print(mUtils.roundToDouble(1.005, 2));
1.0

**Comment by AKushWarrior** [comment]
I'll look into it. Not sure why it's doing that.

**Comment by AKushWarrior** [comment]
It's a floating point error. It'll be fixed in an upcoming 1.0.

**Comment by AKushWarrior** [comment]
@vi-k done as of v1.0.0.
